sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGdN8CEbq4S7t75a3yS
    access-key-secret: CTae8sGH3bRmkq9ZYNzTDSwo9cI0wS
    bucket-name: waks-web-tlias
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx343a59e5b522aad7
    secret: 4e688a33b29135b1b1de00fa6e5b2ad7