sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGdN8CEbq4S7t75a3yS
    access-key-secret: CTae8sGH3bRmkq9ZYNzTDSwo9cI0wS
    bucket-name: waks-web-tlias
  wechat:
    appid: wx343a59e5b522aad7
    secret: 4e688a33b29135b1b1de00fa6e5b2ad7
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:  http://6c3a17ce.r25.cpolar.top/notify/paySuccess
    refundNotifyUrl:  http://6c3a17ce.r25.cpolar.top/notify/refundSuccess
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10